import { createDesiredPropertiesObject } from '@discordeno';

// Create the Desired Bot Properties in RemoveKey Mode.
export const desiredProperties = createDesiredPropertiesObject({
  user: {
    id: true,
    toggles: true,
    username: true,
    globalName: true,
    avatar: true,
    flags: true,
    premiumType: true,
    publicFlags: true,
  },
  guild: {
    id: true,
    name: true,
    owner: true,
    large: true,
    unavailable: true,
    memberCount: true,
    description: true,
    toggles: true,
    shardId: true,
    ownerId: true,
    permissions: true,
    roles: true,
    joinedAt: true,
    members: true,
    channels: true,
  },
  role: {
    id: true,
    guildId: true,
    toggles: true,
    name: true,
    permissions: true,
    flags: true,
  },
  member: {
    id: true,
    toggles: true,
    guildId: true,
    user: true,
    roles: true,
    joinedAt: true,
    permissions: true,
    communicationDisabledUntil: true,
  },
  channel: {
    id: true,
    toggles: true,
    type: true,
    guildId: true,
    name: true,
    flags: true,
    permissionOverwrites: true,
  },
  message: {
    id: true,
    application: true,
    applicationId: true,
    author: true,
    channelId: true,
    content: true,
    attachments: true,
    crosspost: true,
    editedTimestamp: true,
    embeds: true,
    guildId: true,
    interaction: true,
    interactionMetadata: true,
    member: true,
    messageReference: true,
    messageSnapshots: true,
    reactions: true,
    referencedMessage: true,
    type: true,
    webhookId: true,
  },
  interaction: {
    applicationId: true,
    channel: true,
    channelId: true,
    context: true,
    data: true,
    id: true,
    member: true,
    message: true,
    token: true,
    type: true,
    user: true,
  },
  attachment: {
    id: true,
    filename: true,
    title: true,
    size: true,
    url: true,
    proxyUrl: true,
    contentType: true,
    description: true,
    duration_secs: true,
    ephemeral: true,
    flags: true,
    height: true,
    width: true,
    waveform: true,
  },
  emoji: {
    id: true,
    name: true,
    roles: true,
    user: true,
  },
  webhook: {
    id: true,
    name: true,
    guildId: true,
    channelId: true,
    type: true,
  },
});

// Export the BotDesiredProperties Type.
export type BotDesiredProperties = Required<typeof desiredProperties>;
