# Services for Docker Infrastructure
services:
  # Manager for nginx.
  nginxd:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ../infrastructure.d/nginxd:/data
      - ../infrastructure.d/letsencrypt:/etc/letsencrypt
  # Remote Configuration Database
  rconf:
    image: ghcr.io/denoland/denokv
    command: serve
    restart: unless-stopped
    env_file:
      - ../env/infrastructure.env
    environment:
      - DENO_KV_SQLITE_PATH=/d/.denokv.sqlite
    volumes:
      - ../infrastructure.d/database/rconf:/d/
    ports:
      - 4511:4512
  # Deno Production Database
  production:
    image: ghcr.io/denoland/denokv
    command: serve
    restart: unless-stopped
    env_file:
      - ../env/infrastructure.env
    environment:
      - DENO_KV_SQLITE_PATH=/d/.denokv.sqlite
    volumes:
      - ../infrastructure.d/database/production:/d/
    ports:
      - 4512:4512
  # Deno Stage Database
  stage:
    image: ghcr.io/denoland/denokv
    command: serve
    restart: unless-stopped
    env_file:
      - ../env/infrastructure.env
    environment:
      - DENO_KV_SQLITE_PATH=/d/.denokv.sqlite
    volumes:
      - ../infrastructure.d/database/stage:/d/
    ports:
      - 4513:4512
