# Services for Docker Infrastructure
services:
  # Manager for nginx.
  nginxd:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./workspace/proxied:/data
      - ./workspace/letsencrypt:/etc/letsencrypt
  # Remote Configuration Database
  rconf:
    image: ghcr.io/denoland/denokv
    command: serve
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DENO_KV_SQLITE_PATH=/workspace/.denokv.sqlite
    volumes:
      - ./workspace/rconf:/workspace/
    ports:
      - 4511:4512
  production:
    image: ghcr.io/denoland/denokv
    command: serve
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DENO_KV_SQLITE_PATH=/workspace/.denokv.sqlite
    volumes:
      - ./workspace/production:/workspace/
    ports:
      - 4512:4512
  staging:
    image: ghcr.io/denoland/denokv
    command: serve
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DENO_KV_SQLITE_PATH=/workspace/.denokv.sqlite
    volumes:
      - ./workspace/staging:/workspace/
    ports:
      - 4513:4512
