name: Automatic Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  discussions: write
  id-token: write
  packages: write

jobs:
  candidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/xcykrix/arcanis:latest
          docker push ghcr.io/xcykrix/arcanis:latest
